### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HYDROGENLD** [SolarSpec/TaucPlotGUI#2]
When using **only the Segmentation method**, Energy and DAabsCoef and IAabsCoef columns are all NaN, but there is no problem if other Method combinations are selected.
![image](https://github.com/user-attachments/assets/fbb6c2c7-48a8-47cb-8af7-fc5fea74efd4)

**Comment by HarisVidimlic19** [comment]
This was a simple syntax error. I believe the issue is resolved but please raise any other issues you might find. Cheers.
